tap "homebrew/cask"
tap "homebrew/core"
tap "koekeishiya/formulae"
tap "nikitabobko/tap"
brew "gettext"
brew "glib"
brew "jpeg-turbo"
brew "icu4c@78"
brew "icu4c@77"
brew "librsvg"
brew "adwaita-icon-theme"
brew "brotli"
brew "little-cms2"
brew "openexr"
brew "jpeg-xl"
brew "webp"
brew "c-ares"
brew "node"
brew "bitwarden-cli"
brew "btop"
brew "cmake"
brew "cmatrix"
brew "curl"
brew "libavif"
brew "composer"
brew "coreutils"
brew "desktop-file-utils"
brew "exiftool"
brew "exiv2"
brew "fd"
brew "sdl2"
brew "ffmpeg"
brew "libomp", link: true
brew "figlet"
brew "fzf"
brew "gh"
brew "git"
brew "gmic"
brew "pkgconf"
brew "gphoto2"
brew "libheif"
brew "graphicsmagick"
brew "gtk+3"
brew "gtk-mac-integration"
brew "gtk4"
brew "imagemagick"
brew "intltool"
brew "iso-codes"
brew "jq"
brew "json-glib"
brew "just"
brew "kanata"
brew "lazygit"
brew "lensfun"
brew "libraw"
brew "libsecret"
brew "libsoup"
brew "lua"
brew "lua-language-server"
brew "mas"
brew "ninja"
brew "python@3.14"
brew "meson"
brew "neovim"
brew "oh-my-posh"
brew "openjpeg"
brew "osm-gps-map"
brew "perl"
brew "poppler"
brew "portmidi"
brew "potrace"
brew "pugixml"
brew "pygobject3"
brew "resvg"
brew "ripgrep"
brew "sevenzip"
brew "stow"
brew "tmux"
brew "tree"
brew "unzip"
brew "vscode-langservers-extracted"
brew "wget"
brew "yaml-language-server"
brew "yazi"
brew "zellij"
brew "zip"
brew "zoxide"
cask "affinity"
cask "alfred"
cask "appcleaner"
cask "bitwarden"
cask "calibre"
cask "db-browser-for-sqlite"
cask "dbeaver-community"
cask "font-jetbrains-mono-nerd-font"
cask "gimp"
cask "inkscape"
cask "jordanbaird-ice"
cask "launchcontrol"
cask "poedit"
cask "prusaslicer"
cask "raycast"
cask "rectangle"
cask "sf-symbols"
cask "shifty"
cask "steam"
cask "teamviewer"
cask "tuxera-ntfs"
cask "ukelele"
cask "utm"
cask "vlc"
cask "wezterm"
cask "zed"
mas "AdGuard Mini", id: 1440147259
mas "AlignmentForXcode", id: 1168397789
mas "Amphetamine", id: 937984704
mas "Bitwarden", id: 1352778147
mas "Channel Edit for LG TVs", id: 1230066515
mas "DaVinci Resolve", id: 571213070
mas "iMovie", id: 408981434
mas "iXLIFF", id: 944658897
mas "Keynote", id: 409183694
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "TaskPaper", id: 1090940630
mas "Xcode", id: 497799835
mas "XLIFFTool", id: 1074282695
