tap "homebrew/core"
tap "nikitabobko/tap"
brew "gettext"
brew "glib"
brew "jpeg-turbo"
brew "librsvg"
brew "adwaita-icon-theme"
brew "brotli"
brew "little-cms2"
brew "openexr"
brew "webp"
brew "jpeg-xl"
brew "c-ares"
brew "node"
brew "bitwarden-cli"
brew "cmake"
brew "coreutils"
brew "curl"
brew "desktop-file-utils"
brew "exiftool"
brew "exiv2"
brew "fd"
brew "openjpeg"
brew "sdl2"
brew "ffmpeg"
brew "figlet"
brew "fzf"
brew "libavif"
brew "gh"
brew "git"
brew "gmic"
brew "gphoto2"
brew "gtk+3"
brew "gtk-mac-integration"
brew "libheif"
brew "libomp", link: true
brew "libraw"
brew "imagemagick"
brew "intltool"
brew "iso-codes"
brew "jq"
brew "json-glib"
brew "kanata"
brew "lazygit"
brew "lensfun"
brew "libsecret"
brew "libsoup"
brew "lua"
brew "mas"
brew "neovim"
brew "ninja"
brew "oh-my-posh"
brew "osm-gps-map"
brew "perl"
brew "pkgconf"
brew "portmidi"
brew "pugixml"
brew "ripgrep"
brew "stow"
brew "tmux"
brew "tree"
brew "unzip"
brew "vim"
brew "wget"
brew "yazi"
brew "zip"
brew "zoxide"
cask "aerospace"
cask "alfred"
cask "appcleaner"
cask "bitwarden"
cask "calibre"
cask "db-browser-for-sqlite"
cask "dbeaver-community"
cask "font-jetbrains-mono-nerd-font"
cask "gimp"
cask "inkscape"
cask "jordanbaird-ice"
cask "launchcontrol"
cask "poedit"
cask "prusaslicer"
cask "rectangle"
cask "sf-symbols"
cask "shifty"
cask "steam"
cask "teamviewer"
cask "visual-studio-code"
cask "vlc"
cask "wezterm"
mas "AdGuard for Safari", id: 1440147259
mas "Affinity Designer 2", id: 1616831348
mas "Affinity Photo 2", id: 1616822987
mas "AlignmentForXcode", id: 1168397789
mas "Amphetamine", id: 937984704
mas "Bitwarden", id: 1352778147
mas "Channel Edit for LG TVs", id: 1230066515
mas "DaVinci Resolve", id: 571213070
mas "iMovie", id: 408981434
mas "iXLIFF", id: 944658897
mas "Keynote", id: 409183694
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "TaskPaper", id: 1090940630
mas "Xcode", id: 497799835
mas "XLIFFTool", id: 1074282695
vscode "aaron-bond.better-comments"
vscode "alefragnani.bookmarks"
vscode "alefragnani.project-manager"
vscode "arcticicestudio.nord-visual-studio-code"
vscode "azemoh.one-monokai"
vscode "bierner.markdown-emoji"
vscode "bierner.markdown-preview-github-styles"
vscode "catppuccin.catppuccin-vsc"
vscode "chouzz.vscode-better-align"
vscode "dbaeumer.vscode-eslint"
vscode "donjayamanne.githistory"
vscode "dotjoshjohnson.xml"
vscode "dracula-theme.theme-dracula"
vscode "fabiospampinato.vscode-todo-plus"
vscode "fmoronzirfas.open-in-marked"
vscode "galarius.vscode-opencl"
vscode "geddski.macros"
vscode "github.github-vscode-theme"
vscode "idleberg.applescript"
vscode "jgclark.vscode-todo-highlight"
vscode "jock.svg"
vscode "johnpapa.winteriscoming"
vscode "jsynowiec.vscode-insertdatestring"
vscode "kortina.vscode-markdown-notes"
vscode "mohsen1.prettify-json"
vscode "ms-python.debugpy"
vscode "ms-python.isort"
vscode "ms-python.python"
vscode "ms-python.vscode-pylance"
vscode "ms-python.vscode-python-envs"
vscode "ms-vscode-remote.remote-ssh"
vscode "ms-vscode-remote.remote-ssh-edit"
vscode "ms-vscode.cpptools"
vscode "ms-vscode.hexeditor"
vscode "ms-vscode.remote-explorer"
vscode "pkief.material-icon-theme"
vscode "sdras.night-owl"
vscode "stylelint.vscode-stylelint"
vscode "tamasfe.even-better-toml"
vscode "toniapps.gcode"
vscode "twxs.cmake"
vscode "vscodevim.vim"
vscode "whatwedo.twig"
vscode "xaver.clang-format"
vscode "yzhang.markdown-all-in-one"
vscode "zhuangtongfa.material-theme"
