[mgr]
prepend_keymap = [
  { on = [ "g", "s" ],       run = "cd ~/src",         desc = "Go ~/src" },
  { on = "<C-p>",            run = 'shell -- qlmanage -p "$@"',   desc = "Preview file with macOS quicklook" },
]
