set -g default-terminal "$TERM"
# set -ag terminal-overrides ",$TERM:Tc"
set-option -sa terminal-overrides ",xterm*:Tc"

# prefix key
# unbind-key C-b
# set -g prefix C-Space

# Start windows and panes at 1, not 0
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on
setw -g allow-rename off

set -g extended-keys on
set -g extended-keys-format csi-u

set -s set-clipboard on
set -g mouse on

# set vi mode
set-window-option -g mode-keys vi

bind-key -N "Choose session" S choose-session
bind-key -N "New session" N command-prompt -p "New session name:" "new-session -A -s '%%'"

# split panes
bind-key -N "Split window horizontally" v split-window -h -c "#{pane_current_path}"
bind-key -N "Split window verticallySplit" s split-window -v -c "#{pane_current_path}"

# resize panes
bind-key -r -N "Resize pane left" left resize-pane -L 3
bind-key -r -N "Resize pane right" right resize-pane -R 3
bind-key -r -N "Resize pane up" up resize-pane -U 3
bind-key -r -N "Resize pane down" down resize-pane -D 3

# copy mode
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel

# catppuccin
set -g @catppuccin_flavour 'frappe'
set -g @catppuccin_window_status_style 'basic'
set -g @catppuccin_window_default_text " #{window_name}"
set -g @catppuccin_window_text " #{window_name}"
set -g @catppuccin_window_current_text " #{window_name}"
set -g @catppuccin_window_flags "none"
run ~/.config/tmux/plugins/catppuccin/tmux/catppuccin.tmux

set -g mode-style 'bg=#{@thm_surface_2},fg=#{@thm_fg}'
set -g copy-mode-selection-style 'bg=#{@thm_surface_2},fg=#{@thm_fg}'
 
# tmux plugin manager
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'

set -g status-position top
set -g status-left-length 100
set -g status-right-length 100

set -g status-left ""
set -g status-right "#{E:@catppuccin_status_session}"

# Show status bar only if the session has more than 1 window
# set -g status off
# set-hook -g window-linked   'set-option -F status "#{?#{>:#{session_windows},1},on,off}"'
# set-hook -g window-unlinked 'set-option -F status "#{?#{>:#{session_windows},1},on,off}"'

# initialize tmux plugin manager and source all plugins
run ~/.config/tmux/plugins/tpm/tpm

